[package]
name = "embedded-db"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []          # Desktop/dev builds
# For embedded builds: use --no-default-features (removes std)

[dependencies]
heapless = { version = "0.9.1", default-features = false }
